{% set name = "awxkit" %}
{% set version = "23.8.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/awxkit-{{ version }}.tar.gz
  sha256: fb46d23fc019a9b1bedebd9f53ec44d647913a2f6361ae8bafd1d8870156f9b6

build:
  number: 0
  noarch: python
  entry_points:
    - akit=awxkit.scripts.basic_session:load_interactive
    - awx=awxkit.cli:run
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.8
  run:
    - python >=3.8
    - pyyaml
    - requests

test:
  imports:
    - awxkit
    - awxkit.api
  commands:
    - pip check
    - akit --help
    - awx --help
  requires:
    - pip

about:
  home: https://github.com/ansible/awx
  summary: The official command line interface for Ansible AWX
  license: Apache-2.0
  license_file: LICENSE.md
  doc_url: https://docs.ansible.com/ansible-tower/index.html

extra:
  recipe-maintainers:
    - gacallea
