{% set name = "awxkit" %}
{% set version = "23.9.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/awxkit-{{ version }}.tar.gz
  sha256: a9eb91a12dc8e6e69671ad1bf8b9fa096a8b31d7cbe61e14a7ed6102ae509102

build:
  number: 0
  noarch: python
  entry_points:
    - akit=awxkit.scripts.basic_session:load_interactive
    - awx=awxkit.cli:run
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.8
  run:
    - python >=3.8
    - pyyaml
    - requests

test:
  imports:
    - awxkit
    - awxkit.api
  commands:
    - pip check
    - akit --help
    - awx --help
  requires:
    - pip

about:
  home: https://github.com/ansible/awx
  summary: The official command line interface for Ansible AWX
  license: Apache-2.0
  license_file: LICENSE.md
  doc_url: https://docs.ansible.com/ansible-tower/index.html

extra:
  recipe-maintainers:
    - gacallea
